### ISSUE TITLE
Feature Request: ParseFormat option for returning multiple variations

### ISSUE THREAD

**Issue by leononame** [itlightning/dateparse#4]
This is about the `ParseFormat` function. I think this code sums it up best:

```go
package main

import (
	"fmt"

	"github.com/itlightning/dateparse"
)

func main() {
	format, _ := dateparse.ParseFormat("2024-12-31")
	fmt.Println(format)
	format, _ = dateparse.ParseFormat("2024-12-01")
	fmt.Println(format)
	format, _ = dateparse.ParseFormat("2024-12-1")
	fmt.Println(format)
	// Output:
	// 2006-01-02
	// 2006-01-02
	// 2006-01-2
}
```

As you can see, `2024-12-1` parses to `2006-01-2` (the leading 0 removed), but `2024-12-31` parses to `2006-01-02` (a leading zero added even if it's not clear). When using time.Parse in the std lib, this can make a difference. In some cases, multiple formats are able to match a string. It would be great if it'd be possible to extract them all. E.g. for `2024-12-31`, the possible formats would be `[]string{"2006-01-02","2006-01-2","2006-1-02","2006-1-2"}`.

Another thing to consider would be month/day switch-ups. E.g. Parsing the string `01/03/2024` should return both formats `01/02/2006` and `02/01/2006`

**Comment by klondikedragon** [comment]
@leononame - thanks for the feedback and idea!

This library is heavily optimized to produce output that is identical in length to the input as it strives to have very few memory allocations (except for certain edge cases). The normal intent of the library is that you would always call `ParseFormat` each time on the same input string that you pass to `time.Parse`.

So in the examples, if you got back the format string of `2006-01-2` based on the input of `2024-12-1`, then `time.Parse` should properly handle that particular input, and then if you wanted to parse `2024-12-31` instead of passing the previous format string, you would call `ParseFormat` on `2024-12-31` first and then use that format string with `time.Parse`.

This 1:1 matching of call to `ParseFormat` on the same input as call to `time.Parse` is normally not an issue because `ParseFormat` should be very fast in most cases (especially compared to the overhead of the actual `time.Parse` call).

Are there use cases why you'd want to call `ParseFormat` only once on a certain input and then use the resulting format string multiple times on varying inputs? If that is a need, my suggestion would be to have a post-processing function that takes the output of `ParseFormat` and normalizes it based on your need (e.g., if it detects the number `1` in the format string and it's not preceeded by a `0` to insert a `0`, and same thing for the `2`, etc.). What do you think?

**Comment by leononame** [comment]
The post-processing is exactly what I have done now. 

But the reasoning for my request is this: We are processing a large list of possibly dates and need to find a common format in between all of them, not a format that works individually for each date, but instead a single format that works for all of them (or no format at all, if none can be found). To get that to work, we need every possible format for each value and then get the intersection of formats for every value. The problem being, when a single value is returned, this does not work.

E.g., given this list of dates:

```
2020-10-10
2020-11-11
2020-12-12
2020-1-1
2020-2-2
2020-3-3
2020-4-4
2020-12-31
```

You'll get `2006-01-02` (or `2006-02-01`, depending on configuration) for the first three values, then `2006-1-2` or `2006-2-1` and only the last value will give you the information about day/month ordering and resolve to `2006-01-02`. A format that works for all of those dates is `2006-1-2`, but you can't derive it if you only get a single value out of the format.

With the post processing function I have built, this is now working ok, so you can close the Feature Request if you like, but I think it could be a useful feature.

**Comment by klondikedragon** [comment]
thanks @leononame for the details on your use case! the current algorithm is fairly fundamentally tied to single input = single output, it would be a fundamental change to do it differently (at least in terms of memory allocation profile). If you think the post-processing logic could be generalized we could look at including the post-processing into the library itself, but that also feels like that could be hard to generalize broadly. I'll likely close this for now, but open to more ideas.

**Comment by leononame** [comment]
@klondikedragon I don't know what you mean by generalizing. Making a function that returns all "compatible" formats for a given format is not too hard because the number of possible combinations is limited by go's stdlib (e.g. only `2`, `02`, `_2` are allowed for "day of the month". However, I understand if it's not something you'd want to be part of this lib. Go ahead and close the issue :)
